Add author FK non null and user, group FK not null
source-academy/stories-backend pull request #95
Opened 2023-08-07 11:09 UTC by YaleChen299

2023-08-07 14:21 UTC, RichDom2185 reviewed
One of the migration files was in the wrong format (and thus skipped) but somehow the test cases still passed... Let's look into it before merging.

2023-08-07 14:29 UTC, RichDom2185 requested changes
> One of the migration files was in the wrong format (and thus skipped) but somehow the test cases still passed... Let's look into it before merging.

I looked into it... the tests still passed because we enforce a non-null constraint in the model layer (because it's typed `uint` not `*uint`). So regardless of whether or not the DB has a non-null constraint, inserting empty will fail due to 0 being an FK violation.

Even with the migration file fixed, the insert fails not because of the null constraint violation, but instead because of the FK violation (inserting 0).

I think we should use `db.Exec` or `db.Raw` instead of relying on the model to test. That way, we can test for both behaviors: null  constraint violation as well as FK violation.

Thoughts? @YaleChen299

2023-08-07 14:29 UTC, RichDom2185 commented on model/stories_test.go
> +	})
I think we can do better and check for the error specifically being an FK violation or a null constraint violation.

2023-08-07 14:29 UTC, RichDom2185 commented on model/usergroups_test.go
> +	})
Ditto on checking the error type.

2023-08-08 07:44 UTC, YaleChen299 commented
> > One of the migration files was in the wrong format (and thus skipped) but somehow the test cases still passed... Let's look into it before merging.
> 
> I looked into it... the tests still passed because we enforce a non-null constraint in the model layer (because it's typed `uint` not `*uint`). So regardless of whether or not the DB has a non-null constraint, inserting empty will fail due to 0 being an FK violation.
> 
> Even with the migration file fixed, the insert fails not because of the null constraint violation, but instead because of the FK violation (inserting 0).
> 
> I think we should use `db.Exec` or `db.Raw` instead of relying on the model to test. That way, we can test for both behaviors: null constraint violation as well as FK violation.
> 
> Thoughts? @YaleChen299

Yup I agree. I will do it. I was just a bit lazy hahaha.

2023-08-09 12:55 UTC, merged