add course group mapping
source-academy/stories-backend pull request #97
Opened 2023-08-10 07:53 UTC by YaleChen299

2023-08-10 08:04 UTC, RichDom2185 requested changes
I'm not too sure, what's the rationale of using the course ID as a primary key, especially since we already have an ID column? What would happen if a course wants to have multiple groups in the future?

If it's simply to enforce the uniqueness, I would argue it's better to create a unique index, and just drop/modify it later if we want to support the has-many relationship.

2023-08-10 08:04 UTC, RichDom2185 commented on migrations/20230810152313-add_course_groups.sql
Can we add a unique index on the course ID? It's fine if we drop it later but for now since the rest of the code is working under assumptions I think it would be good to add it.

2023-08-10 08:04 UTC, RichDom2185 commented on migrations/20230810152313-add_course_groups.sql
> +DROP TABLE IF EXISTS user_groups;
Wrong table name.

2023-08-10 08:04 UTC, RichDom2185 commented on migrations/20230810152313-add_course_groups.sql
> +    deleted_at  deleted_at_type,
Let's remove the double space.

2023-08-10 08:04 UTC, RichDom2185 commented on migrations/20230810152313-add_course_groups.sql
> +    id SERIAL,
Shouldn't this be the primary key?

2023-08-10 08:13 UTC, YaleChen299 commented
> I'm not too sure, what's the rationale of using the course ID as a primary key, especially since we already have an ID column? What would happen if a course wants to have multiple groups in the future?
> 
> If it's simply to enforce the uniqueness, I would argue it's better to create a unique index, and just drop/modify it later if we want to support the has-many relationship.

My main thought process is that this feature is just one for some default view just like the `last_viewed_course` in the main backend, so we just need one default one that ties to the course. That's why I think it is just a table that uses course as a key. I don't think we really need that many course to one group feature though. When we have more groups the group is just like a channel that you subscribed to. We just need to show all groups joined by a user and the user can switch group.

2023-08-13 06:35 UTC, RichDom2185 reviewed
Can we add tests for `coursegroups.go`? Otherwise, we can ignore the other TODOs I've just added.

Thanks!

2023-08-14 09:35 UTC, RichDom2185 approved these changes
LGTM, thanks!

2023-08-14 09:36 UTC, merged